name = "Delivery Custom"
type = "delivery_customization"
api_version = "2023-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/delivery-customization/:functionId/new"
details = "/delivery-customization/:functionId/:id"